"""Hand-authored English query bank for the intent classifier.

Every string below is written deliberately by an author (not produced by
slot-filling), so each is grammatical, semantically sensible, and labeled
by *user intent* per docs/annotation-spec.md:

- question:    seeks a specific answer (a yes/no or a value).
- exploratory: open-ended exploration, no single factual answer.
- claim:       a factual assertion to be checked (subject + predicate).
- retrieval:   a document / keyword / data lookup.
- unknown:     out of EEA scope, code-switched, or gibberish.

These are the anchor-language rows. Each gets a stable id at serialization
time so native translations can be attached per row for the other 27
languages later, without disturbing the English set.
"""

QUESTION = [
    "What is air pollution?",
    "What exactly is PM2.5?",
    "What is the difference between PM2.5 and PM10?",
    "What is PFAS and why is it a problem?",
    "What is the ozone layer?",
    "What is biodiversity?",
    "What does an urban heat island mean?",
    "What is the European Green Deal?",
    "What is the EU's main climate law?",
    "How does air pollution affect the lungs?",
    "How do fine particles get into the bloodstream?",
    "How does climate change affect the sea?",
    "How is water quality measured in rivers?",
    "How do we know deforestation is happening?",
    "How does urban heat form in cities?",
    "How much of Europe's electricity comes from wind?",
    "How many nature reserves are there in the EU?",
    "How long does plastic take to break down?",
    "How is PM2.5 formed in cities?",
    "Why does traffic cause air pollution?",
    "Why is the ozone layer important?",
    "Why are wetlands so important for biodiversity?",
    "Why is nitrate a problem in drinking water?",
    "Why are heatwaves getting more frequent?",
    "Why do cities get hotter than the countryside?",
    "Why is PFAS called the forever chemical?",
    "Why does shipping pollute the air?",
    "Why is deforestation a problem in Europe?",
    "Where is air pollution worst in Europe?",
    "Where do most of Europe's microplastics come from?",
    "Where is the EU's climate department based?",
    "Where does nitrate in groundwater come from?",
    "Where are the last primeval forests in Europe?",
    "Where does the Danube get polluted?",
    "When was the Paris Agreement signed?",
    "When is air pollution usually worst?",
    "When does smog season happen in Europe?",
    "When will the EU reach climate neutrality?",
    "When were single-use plastics banned?",
    "Which country has the best air quality in Europe?",
    "Which country produces the most wind power?",
    "Which cities have the worst winter smog?",
    "Which industries pollute water the most?",
    "Which EU country has the most forests?",
    "Which river is the most polluted in the EU?",
    "Who monitors air quality in the EU?",
    "Who pays for waste collection in Europe?",
    "Who is responsible for cleaning up PFAS?",
    "Is smog dangerous for children?",
    "Is drinking water safe across the EU?",
    "Is the air in London cleaner than in Warsaw?",
    "Is plastic in the ocean hurting fish?",
    "Is the ozone layer healing?",
    "Is recycling actually good for the planet?",
    "Is it legal to burn wood in an EU city?",
    "Does heating a house with oil pollute the air?",
    "Does air conditioning make urban heat worse?",
    "Do electric planes exist yet?",
    "Do bees suffer from pesticide use?",
    "Can we reverse climate change?",
    "Can cities be cooled without air conditioning?",
    "Can plastic be fully recycled?",
    "Can we still save the coral reefs?",
    "Should the EU ban more cars from city centres?",
    "Should plastic bags be banned again?",
    "Should the EU fund more reforestation?",
    "Will Europe be flooded by 2050?",
    "Will air quality improve if we cut traffic?",
    "Will renewables be cheaper by 2030?",
    "Is it true that Poland has the worst air quality?",
    "Is it true that the Mediterranean is warming faster than the rest of the ocean?",
    "How bad is the air in Paris in winter?",
    "How much CO2 does a European emit per year?",
    "How much has the Arctic shrunk?",
    "How far do fine particles travel?",
    "How many species are lost each year?",
    "What is the EU doing about plastic in the sea?",
    "What are the main sources of CO2 in Europe?",
    "What is the biggest threat to the Danube?",
    "What causes smog in winter?",
    "What is a carbon budget?",
    "What is the difference between weather and climate?",
    "What is a nature-based solution?",
    "What is the EU target for renewables by 2030?",
    "How does nitrate get into drinking water?",
    "How do airports affect local air quality?",
    "Why do some cities smell of diesel?",
    "Why is the North Sea losing species?",
    "Why do floods seem to happen more often now?",
    "Why is lead still found in old paint?",
    "Where is the air cleanest in Europe?",
    "Where does Europe get its heat from?",
    "When does the EU measure its climate progress?",
    "Which metals are dangerous in water?",
    "Who made the first air quality index?",
    "Is wild swimming safe in EU rivers?",
    "Is my town's water safe to drink?",
    "Does farming cause more pollution than traffic?",
    "Do trees in cities really cool the air?",
    "Can we eat fish from the Baltic safely?",
    "Should I buy a heat pump for my house?",
    "Will the EU hit its 2030 climate target?",
    "What do satellites show about European forests?",
    "What is the healthiest way to heat a home?",
    "How does drought affect drinking water?",
    "How do we measure the health of a forest?",
    "Why do some EU summers feel longer?",
    "Why is the Adriatic getting more algae?",
    "Where do microplastics in the Alps come from?",
    "When were the first air quality limits set?",
    "Which fuel pollutes the least per kilometre?",
    "Who funds the climate satellites in Europe?",
    "Is a wood stove cleaner than a diesel generator?",
    "Is the EU ahead on green hydrogen?",
    "Do new buildings have to be energy efficient?",
    "Can we trust the official air quality data?",
    "Should EU farmers be paid to plant trees?",
    "Will sea levels reach the coast by 2100?",
    "What is a circular economy?",
    "What is the EU's plastic tax?",
]
EXPLORATORY = [
    "Causes of urban smog",
    "Effects of air pollution on children's health",
    "Overview of EU climate policy",
    "Trends in European deforestation",
    "How renewable energy works",
    "Compare wind and solar power",
    "Status of biodiversity in Europe",
    "The state of the Mediterranean",
    "Plastic waste in European rivers",
    "Heatwaves and the human body",
    "Drivers of nitrate pollution",
    "The role of forests in the climate",
    "Progress on the EU's 2030 targets",
    "Solutions for winter smog",
    "The economics of waste incineration",
    "Challenges of rewilding Europe",
    "How cities plan for heat",
    "The future of European rivers",
    "PFAS in consumer products",
    "Air quality in Eastern Europe",
    "Water scarcity in Southern Europe",
    "The politics of the carbon border tax",
    "Innovation in battery storage",
    "How the EU tracks ocean health",
    "Inequality in pollution exposure",
    "The history of the ozone hole",
    "Rewilding the Danube",
    "Microplastics in food",
    "The cost of inaction on climate",
    "How farmers affect water quality",
    "Transport and its carbon footprint",
    "The health of the Baltic Sea",
    "Urban trees and their benefits",
    "The science of air particulates",
    "Europe's renewable energy mix",
    "How to read an air quality index",
    "The impact of shipping on the Arctic",
    "Green infrastructure in cities",
    "The lifecycle of a plastic bottle",
    "Wildfires in the Mediterranean",
    "How drought forms in summer",
    "The role of wetlands in flood control",
    "Carbon capture and storage",
    "European electricity in 2050",
    "How noise pollution affects health",
    "The transition to electric transport",
    "Light pollution and the night sky",
    "How the EU funds green research",
    "Soil health in Europe",
    "The link between heat and asthma",
    "How to reduce a household's carbon footprint",
    "The state of European honeybees",
    "Flood risk in the Rhine basin",
    "The value of urban green spaces",
    "How desalination works",
    "The impact of tourism on nature",
    "European forest fires since 2000",
    "How algae blooms form",
    "The trade-offs of nuclear power",
    "Sustainable fishing in the EU",
    "The geography of European drought",
    "How heat pumps save energy",
    "The impact of agriculture on the climate",
    "European air quality since 1990",
    "The case for urban forests",
    "How we measure carbon sinks",
    "The future of European coasts",
    "How plastic decomposes in the sea",
    "The role of citizens in climate action",
    "Water use in European agriculture",
    "The health benefits of clean air",
    "How cities manage stormwater",
    "The impact of aviation on the climate",
    "European energy in winter",
    "How to think about a low-carbon diet",
    "The state of the Alpine glaciers",
    "How the EU classifies protected areas",
    "The impact of oil spills",
    "Green roofs and their effects",
    "How we count Europe's species",
    "The economics of the circular economy",
    "Heat adaptation in older people",
    "The role of science in climate policy",
    "How rivers carry plastic to the sea",
    "European nature in the 21st century",
    "The impact of air freight",
    "How we assess water scarcity",
    "The future of European farming",
    "The health of urban trees",
    "How the carbon market works",
    "The impact of tourism on the Alps",
    "European winter air pollution",
    "How we protect marine species",
    "The role of insurance in flood risk",
    "How to plan a green city",
    "The impact of microplastics on soil",
    "European nature restoration plans",
    "How heat affects sleep",
    "The future of European hydropower",
    "The impact of construction on air quality",
]
CLAIM = [
    "Air pollution causes premature deaths",
    "Traffic is the main source of city smog",
    "Plastic is now found in human blood",
    "The ozone layer is slowly healing",
    "Nitrate levels in groundwater are still too high",
    "Climate change is making European floods worse",
    "Electric cars do not fully solve air pollution",
    "Renewable energy is now the cheapest source of electricity",
    "Deforestation in Europe is faster than replanting",
    "Heatwaves are killing more Europeans every year",
    "The EU is missing its 2030 climate target",
    "Microplastics have reached the deepest part of the ocean",
    "Farming is the biggest source of nitrate pollution",
    "Cities are on average two degrees hotter than the countryside",
    "The Green Deal has cut Europe's emissions",
    "Single-use plastic bans have not reduced litter",
    "Wind power now beats coal in several EU countries",
    "The Mediterranean is warming faster than most of the ocean",
    "Bees are declining across Europe",
    "Air quality in Eastern Europe is still below safe limits",
    "The Danube carries more plastic to the Black Sea than any other river",
    "Recycling actually increases carbon emissions",
    "The European Green Deal is too slow",
    "Coal is still the EU's biggest source of CO2",
    "Droughts are getting longer in Southern Europe",
    "Wood stoves are a leading cause of winter PM2.5",
    "The Arctic is warming four times faster than the rest of the world",
    "Plastic in the sea is now a bigger threat than oil",
    "Urban trees reduce hospital visits for asthma",
    "The EU leads the world in wind capacity",
    "Most of Europe's water is used by agriculture",
    "PFAS is found in a third of EU drinking water",
    "Heat-related deaths have tripled since 2000",
    "The Baltic Sea is too rich in nutrients",
    "Electric heating will double Europe's electricity demand",
    "Reforestation can store billions of tonnes of carbon",
    "The EU is the world's biggest exporter of plastic waste",
    "Glaciers in the Alps will be gone by 2100",
    "Shipping is the most polluting form of transport",
    "Air pollution shortens European life by years",
    "The carbon border tax will protect EU industry",
    "Urban sprawl is destroying European farmland",
    "The sea is acidifying faster than corals can adapt",
    "The EU's recycling target is too easy",
    "Nitrogen is a bigger problem than CO2 for nature",
    "Europe's forests are absorbing less carbon",
    "The heat pump boom is straining the grid",
    "Floods cost Europe billions every year",
    "The Mediterranean is becoming a desert",
    "EV batteries have a serious waste problem",
    "Europe's wildlife is recovering in protected areas",
    "The EU wastes a fifth of all food",
    "Air from the North Sea brings salt to coastal cities",
    "The Paris Agreement has not slowed emissions enough",
    "Lead is still dangerous in old European buildings",
    "The EU's plastic tax has barely changed behaviour",
    "Solar is now the cheapest electricity in history",
    "The Alps are losing a third of their glacier mass",
    "European rivers are running cleaner than in 1990",
    "The Green Deal will create millions of jobs",
    "Ocean plastics are now in the salt we eat",
    "Cities will be unlivable without cooling by 2050",
    "The EU's forest fires are getting worse every decade",
    "Nitrate from farming contaminates a fifth of EU water",
    "The ozone hole has closed over the Arctic",
    "Europe's coasts are eroding faster than expected",
    "The carbon market has failed to cut emissions",
    "Wildfires will reach new European cities by 2040",
    "The EU is now a net importer of fossil fuels",
    "Algae blooms are deadlier every summer",
    "Replanted forests never match the original",
    "Europe's air has halved its sulphur dioxide",
    "The heat island effect doubles night-time deaths in heatwaves",
    "The EU's nature targets are unachievable",
    "Desalination is too energy-intensive to scale",
    "The EU is the world's largest donor for reforestation",
    "Urban heat is making European nights unsleepable",
    "The Green Deal has slowed down under the current council",
    "European farmland is losing half its insects",
    "The carbon footprint of a European diet is falling",
    "The EU's waste targets are too strict for Eastern Europe",
    "Coastal cities will lose a tenth of their value to flooding",
    "The EU's hydrogen strategy is over-promising",
    "Europe's beech forests are dying of drought",
    "The sea level rise will displace coastal villages",
    "The EU is behind the US on battery production",
    "The Adriatic is losing its seagrass meadows",
    "Europe's last wild rivers are under threat",
    "The carbon border tax will push prices up",
    "The EU's solar boom is outpacing grid upgrades",
    "European cities are greening faster than promised",
    "The ozone layer will fully recover by 2050",
    "The EU's water framework is failing",
    "Forest fires will make the Mediterranean uninhabitable",
    "The EU leads the world in green bonds",
    "Europe's rivers are losing their salmon",
    "The heat pump shortage will delay winter heating",
    "The EU's plastic waste is doubling every decade",
    "Coastal flooding will triple in Europe by 2050",
    "The EU's forest cover is at a record high",
]
RETRIEVAL = [
    "SOER 2025",
    "climate change 2024",
    "air quality index",
    "PM2.5 data",
    "European Green Deal",
    "waste statistics",
    "climate adaptation strategy",
    "water quality report",
    "biodiversity indicators",
    "ozone layer fact sheet",
    "renewable energy statistics",
    "plastic pollution map",
    "deforestation data",
    "urban heat map",
    "nitrate levels 2022",
    "CO2 emissions by country",
    "microplastics report",
    "EU climate law",
    "flood risk map",
    "marine litter statistics",
    "air pollution health effects",
    "river quality index",
    "forest cover Europe",
    "heatwave mortality data",
    "PFAS in drinking water",
    "wind capacity 2023",
    "solar capacity 2023",
    "carbon border tax",
    "green deal targets",
    "nature restoration law",
    "waste incineration data",
    "transport emissions",
    "agricultural nitrate",
    "sea level rise projections",
    "glacier mass balance",
    "species extinction rate",
    "biodiversity strategy 2030",
    "air quality limits",
    "PM10 guidelines",
    "NO2 limits",
    "drinking water directive",
    "urban trees census",
    "plastic tax",
    "circular economy action plan",
    "renewable energy directive",
    "emissions trading system",
    "carbon budget",
    "climate neutrality action plan",
    "floods directive",
    "water framework directive",
    "habitat directive",
    "birds directive",
    "marine strategy framework",
    "air quality directive",
    "industrial emissions directive",
    "land use statistics",
    "land cover map",
    "population by region",
    "GDP by country",
    "energy consumption by sector",
    "electricity price",
    "gas consumption",
    "oil imports",
    "CO2 per capita",
    "per capita emissions",
    "transport mode share",
    "car ownership",
    "public transport usage",
    "building energy certificates",
    "heat pump sales",
    "EV sales",
    "EV charging points",
    "recycling rate",
    "food waste",
    "waste per capita",
    "incineration capacity",
    "landfill statistics",
    "composting data",
    "urban green space",
    "tree canopy coverage",
    "albedo data",
    "heat island intensity",
    "night temperature",
    "drought index",
    "soil moisture",
    "precipitation data",
    "temperature records",
    "heatwave frequency",
    "frost days",
    "growing season length",
    "river discharge",
    "groundwater level",
    "aquifer data",
    "desalination capacity",
    "water use by sector",
    "irrigation data",
    "crop yield",
    "agricultural land",
    "forest area",
    "protected areas list",
]
UNKNOWN = [
    "best time to visit Lisbon",
    "how to boil an egg",
    "who is the prime minister of Japan",
    "what is the capital of Canada",
    "recipe for pasta carbonara",
    "stock market crash of 2008",
    "what is the score of the Champions League final",
    "best laptop for video editing",
    "how do I reset my wifi router",
    "who wrote the book Sapiens",
    "pollution qualité",
    "smog aria",
    "klimat förändring climate",
    "zorpflimble",
    "asdfghjkl",
    "blargh blargh zorp",
    "https://eea.example/air",
    "the meaning of life is",
    "12 34 56 78 90",
    "!!! ??? ...",
    "what is the weather in New York",
    "how to fix a leaky tap",
    "who won the 2022 world cup",
    "best restaurants in Rome",
    "how old are the pyramids",
    "what is the population of India",
    "how to learn Spanish",
    "what is the tallest mountain",
    "best football players",
    "how to bake bread",
    "what is the currency of Japan",
    "who is the president of Brazil",
    "how to tie a tie",
    "what is the distance to the moon",
    "best board games",
    "how to grow tomatoes",
    "what is the largest ocean",
    "who painted the Mona Lisa",
    "how to change a tyre",
    "what is the national animal of Australia",
]
